eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9001

spring:
  application:
    name: example-project-a
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./dbfile/a
    username: root
    password: root
    platform: h2
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

